export const PDF_PAGE_VISIBILITY_THRESHOLD = 0.05;
export const PDF_PAGE_OBSERVER_ROOT_MARGIN = "800px 0px";
export const PDF_PAGE_OBSERVER_THRESHOLDS = [0, 0.05, 0.1, 0.25, 0.5, 0.75, 1];
export const PDF_PAGE_WINDOW_SIZE = 6;
export const PDF_PAGE_PLACEHOLDER_FALLBACK_HEIGHT = 200;