const LOCALDB_SCHEMA_VERSION_FOR_NAME = 19;
const LOCALDB_GENERATION_MAX = 3;
const LOCALDB_GENERATION_KEY_PREFIX = "flashcard.localdb.generation.";
const LOCALDB_NAME_PREFIX = "FlashcardMasterDB_";
const LOCALDB_RECOVERY_GUIDE_URL = "https://support.google.com/chrome/answer/2392709";

export { LOCALDB_GENERATION_KEY_PREFIX, LOCALDB_GENERATION_MAX, LOCALDB_NAME_PREFIX, LOCALDB_RECOVERY_GUIDE_URL, LOCALDB_SCHEMA_VERSION_FOR_NAME };
