export const PDF_PAGE_RENDER_OVERSCAN_VIEWPORTS = 1.25;
export const PDF_PAGE_PREFETCH_OVERSCAN_VIEWPORTS = 2.25;
export const PDF_PAGE_PREFETCH_EXTRA_PAGES = 1;
export const PDF_PAGE_PLACEHOLDER_FALLBACK_HEIGHT = 200;
