substitutions:
  _REGION: asia-northeast1
  _SERVICE: sivflow-api
  _SOURCE: functions

steps:
  - id: deploy-cloud-run-from-source
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --source
      - ${_SOURCE}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - NODE_ENV=production

options:
  logging: CLOUD_LOGGING_ONLY
