export const EXPLORER_ACTION_TYPES = {
  APPLY_ROUTE_STATE: "APPLY_ROUTE_STATE",
  SELECT_FOLDER: "SELECT_FOLDER",
  SELECT_ITEM: "SELECT_ITEM",
  SELECT_ROOT_ITEM: "SELECT_ROOT_ITEM",
  RESET_FOR_HOME_MODE: "RESET_FOR_HOME_MODE",
  SET_BREADCRUMB_CONTEXT: "SET_BREADCRUMB_CONTEXT",
  NAVIGATE_TO_SECTION_LIST: "NAVIGATE_TO_SECTION_LIST",
} as const;

export type ExplorerActionType =
  (typeof EXPLORER_ACTION_TYPES)[keyof typeof EXPLORER_ACTION_TYPES];
