const PDF_TRACKPAD_ZOOM_SENSITIVITY = 0.0015;
const PDF_ZOOM_BUTTON_SCALE_FACTOR = 1.1;
const PDF_ZOOM_MAX_SCALE = 5;
const PDF_ZOOM_MIN_SCALE = 0.25;
const PDF_ZOOM_SCALE_EPSILON = 0.001;
const PDF_ZOOM_STEP = 0.2;



export { PDF_TRACKPAD_ZOOM_SENSITIVITY, PDF_ZOOM_BUTTON_SCALE_FACTOR, PDF_ZOOM_MAX_SCALE, PDF_ZOOM_MIN_SCALE, PDF_ZOOM_SCALE_EPSILON, PDF_ZOOM_STEP };
