import { CANONICAL_CARD_WIDTH } from "./geometry";
import {
  CARD_PANE_AUTO_MAX_SCALE,
  CARD_PANE_EDIT_DEFAULT_WIDTH_PX,
  CARD_PANE_EDIT_MIN_WIDTH_PX,
  CARD_PANE_VIEW_DEFAULT_WIDTH_PX,
  CARD_PANE_VIEW_MIN_WIDTH_PX,
  CARD_PANE_WIDTH_STEP_PX,
} from "./paneWidth";

export const CARD_SET_VIEW_PAGER_PADDING_INLINE = 0;
export const CARD_SET_VIEW_PAGER_PADDING_BLOCK = "50vh";
export const CARD_SET_VIEW_NATURAL_INDEX_COMMIT_DELAY_VIEW_MS = 0;
export const CARD_SET_VIEW_NATURAL_INDEX_COMMIT_DELAY_EDIT_MS = 0;

export type CardViewZoomInteractionSource =
  | "slider"
  | "button"
  | "wheel"
  | "gesture";

export const CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE = {
  slider: 1,
  button: 5,
  wheel: 1,
  gesture: 1,
} as const satisfies Record<CardViewZoomInteractionSource, number>;

export const CARD_VIEW_ZOOM_SLIDER_STEP_PERCENT =
  CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE.slider;

export const CARD_VIEW_ZOOM_BUTTON_STEP_PERCENT =
  CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE.button;

export const CARD_VIEW_ZOOM_WHEEL_STEP_PERCENT =
  CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE.wheel;

export const CARD_VIEW_ZOOM_GESTURE_STEP_PERCENT =
  CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE.gesture;

/**
 * 既存コード互換用。
 * 旧来の `CARD_VIEW_ZOOM_STEP_PERCENT` は coarse step の意味で使われていたため、
 * button step を alias として残す。
 */
export const CARD_VIEW_ZOOM_STEP_PERCENT = CARD_VIEW_ZOOM_BUTTON_STEP_PERCENT;

export const CARD_VIEW_ZOOM_DEFAULT_PERCENT = Math.round(
  (CARD_PANE_VIEW_DEFAULT_WIDTH_PX / CANONICAL_CARD_WIDTH) * 100,
);

export const CARD_VIEW_ZOOM_MIN_PERCENT = Math.round(
  (CARD_PANE_VIEW_MIN_WIDTH_PX / CANONICAL_CARD_WIDTH) * 100,
);

export const CARD_VIEW_DEFAULT_ZOOM_PERCENT = CARD_VIEW_ZOOM_DEFAULT_PERCENT;
export const CARD_VIEW_MIN_ZOOM_PERCENT = CARD_VIEW_ZOOM_MIN_PERCENT;

export {
  CARD_PANE_AUTO_MAX_SCALE,
  CARD_PANE_EDIT_DEFAULT_WIDTH_PX,
  CARD_PANE_EDIT_MIN_WIDTH_PX,
  CARD_PANE_VIEW_DEFAULT_WIDTH_PX,
  CARD_PANE_VIEW_MIN_WIDTH_PX,
  CARD_PANE_WIDTH_STEP_PX,
};