import { CANONICAL_CARD_WIDTH } from "./geometry";
import {
  CARD_PANE_AUTO_MAX_SCALE,
  CARD_PANE_EDIT_DEFAULT_WIDTH_PX,
  CARD_PANE_EDIT_MIN_WIDTH_PX,
  CARD_PANE_VIEW_DEFAULT_WIDTH_PX,
  CARD_PANE_VIEW_MIN_WIDTH_PX,
  CARD_PANE_WIDTH_STEP_PX,
} from "./paneWidth";

export const CARD_SET_VIEW_PAGER_PADDING_INLINE = 0;
export const CARD_SET_VIEW_PAGER_PADDING_BLOCK = "50vh";
export const CARD_SET_VIEW_NATURAL_INDEX_COMMIT_DELAY_VIEW_MS = 0;
export const CARD_SET_VIEW_NATURAL_INDEX_COMMIT_DELAY_EDIT_MS = 0;

export const CARD_VIEW_ZOOM_STEP_PERCENT = 5;
export const CARD_VIEW_ZOOM_DEFAULT_PERCENT = Math.round(
  (CARD_PANE_VIEW_DEFAULT_WIDTH_PX / CANONICAL_CARD_WIDTH) * 100,
);
export const CARD_VIEW_ZOOM_MIN_PERCENT = Math.round(
  (CARD_PANE_VIEW_MIN_WIDTH_PX / CANONICAL_CARD_WIDTH) * 100,
);

export const CARD_VIEW_DEFAULT_ZOOM_PERCENT = CARD_VIEW_ZOOM_DEFAULT_PERCENT;
export const CARD_VIEW_MIN_ZOOM_PERCENT = CARD_VIEW_ZOOM_MIN_PERCENT;
