import React, { useCallback, useEffect, useId, useMemo, useRef, useState } from "react";
import { Button } from "@/chip/ui/button/button";
import { Slider } from "@/chip/ui/slider";
import { ImageFrame } from "@/components/card/blocks/image/ImageFrame";
import { useAuthSession } from "@/contexts/auth/useAuthSession";
import { CANONICAL_CARD_WIDTH } from "@/domain/card/cardGeometry.constants";
import type { ResolvedCardImage } from "@/services/cardImageResolver";
import { resolveCardImageUrl } from "@/services/cardImageResolver";
import { getOrCreateImageBlobUrl, removeImageBlobUrl } from "@/services/imageBlobUrlSessionCache";
import { deleteImageBlob, getImageBlob, putImageBlob } from "@/services/imageFileStore";
import { getLocalDb } from "@/services/localdb";
import { persistentQueue } from "@/services/PersistentOfflineQueue";
import type { AssetRecord, UploadedImage } from "@/types";
import { Check, RotateCcw, Upload, X } from "@/chip/icons/icons";
import { loadImageNaturalSize } from "@/utils/uploaded-image/naturalSize.utils";
