
// colors (weekday grid specific)
const WEEKDAY_COLOR_PRIMARY = "rgba(24, 95, 165, 0.85)";
const WEEKDAY_COLOR_PRIMARY_SOFT = "rgba(24, 95, 165, 0.45)";
const WEEKDAY_COLOR_TODAY_BG = "#f0f6ff";
const WEEKDAY_COLOR_SELECTED_BG = "#2d3039";
const WEEKDAY_COLOR_HOVER_BG = "#f4f5f7";
const WEEKDAY_COLOR_TEXT_PRIMARY = "#24231f";
const WEEKDAY_COLOR_TEXT_SECONDARY = "#8f929c";
const WEEKDAY_COLOR_TEXT_MUTED = "#b0b4be";
const WEEKDAY_COLOR_BORDER_MAIN = "#eee";
const WEEKDAY_COLOR_BORDER_SUB = "#f4f4f4";



export { WEEKDAY_COLOR_PRIMARY, WEEKDAY_COLOR_PRIMARY_SOFT, WEEKDAY_COLOR_TODAY_BG, WEEKDAY_COLOR_SELECTED_BG, WEEKDAY_COLOR_HOVER_BG, WEEKDAY_COLOR_TEXT_PRIMARY, WEEKDAY_COLOR_TEXT_SECONDARY, WEEKDAY_COLOR_TEXT_MUTED, WEEKDAY_COLOR_BORDER_MAIN, WEEKDAY_COLOR_BORDER_SUB };
