import { hasDesktopRuntime } from "@/platform/detectDesktopBridge";



type WeekdayHourLabelMode = "full" | "integer";



//Month
const MONTH_GRID_WEEKDAY_HEADER_HEIGHT_CLASS = "h-8";
const MONTH_GRID_DAY_HEADER_POSITION_CLASS = "left-0 top-0 md:left-3 md:top-1";
const MONTH_GRID_EVENTS_CONTAINER_POSITION_CLASS = "inset-x-px top-8";
const MONTH_GRID_EVENTS_GAP_CLASS = "gap-0.5";
const MONTH_GRID_OVERFLOW_TEXT_CLASS = "w-full pr-3 text-right text-xs leading-none";
//Daydetail
const DAY_DETAIL_HEADER_HEIGHT_CLASS = "h-8";
const DAY_DETAIL_TIME_LABEL_WIDTH_CLASS = "w-12";
const DAY_DETAIL_EVENT_PADDING_CLASS = "px-2 py-1";
const DAY_DETAIL_EVENT_RADIUS_CLASS = "rounded-md";
const DAY_DETAIL_EVENT_TEXT_CLASS = "text-xs";
const DAY_DETAIL_SCROLL_AREA_CLASS = "overflow-y-auto";
const DAY_DETAIL_CURRENT_TIME_LINE_CLASS = "left-12 right-0 h-px";
const DAY_DETAIL_CURRENT_TIME_LABEL_CLASS = "-translate-y-1/2 text-xs";
// WeekDay

// time / grid
const WEEKDAY_DESKTOP_HOUR_LABEL_MODE: WeekdayHourLabelMode = "full";
const WEEKDAY_MOBILE_WEB_HOUR_LABEL_MODE: WeekdayHourLabelMode = "integer";
const IS_MOBILE_WEB_VIEWPORT = typeof window !== "undefined" && window.innerWidth <= 767;
const WEEKDAY_HOURS = 24;
const WEEKDAY_MINUTES_PER_HOUR = 60;
const WEEKDAY_HOUR_LABEL_MODE = hasDesktopRuntime() || !IS_MOBILE_WEB_VIEWPORT ? WEEKDAY_DESKTOP_HOUR_LABEL_MODE : WEEKDAY_MOBILE_WEB_HOUR_LABEL_MODE;
const WEEKDAY_DAY_FORMAT = "E";
const WEEKDAY_DATE_FORMAT = "d";
const WEEKDAY_GRID_TIME_COLUMN_Z_INDEX = 20;
// timing (current time hook)
const WEEKDAY_CURRENT_TIME_UPDATE_INTERVAL_MS = 60_000;
const WEEKDAY_SECONDS_PER_MINUTE = 60;
const WEEKDAY_MS_PER_SECOND = 1000;
// layout css vars
const WEEKDAY_CSS_VAR_HOUR_ROW_HEIGHT = "--calendar-hour-row-height" as const;
const WEEKDAY_CSS_VAR_EVENT_START_HOUR = "--calendar-event-start-hour" as const;
const WEEKDAY_CSS_VAR_EVENT_DURATION_HOURS = "--calendar-event-duration-hours" as const;
const WEEKDAY_CURRENT_TIME_INDICATOR_HEIGHT = 1.5;
const WEEKDAY_CURRENT_TIME_DASHED_STYLE = "1.5px dashed";
// hour label
const WEEKDAY_HOUR_LABEL_PADDING_RIGHT = "0.625rem";
const WEEKDAY_HOUR_LABEL_FONT_SIZE = "11px";
// misc layout
const WEEKDAY_EVENT_CHIP_PADDING_X = 2;



export { MONTH_GRID_WEEKDAY_HEADER_HEIGHT_CLASS, MONTH_GRID_DAY_HEADER_POSITION_CLASS, MONTH_GRID_EVENTS_CONTAINER_POSITION_CLASS, MONTH_GRID_EVENTS_GAP_CLASS, MONTH_GRID_OVERFLOW_TEXT_CLASS, DAY_DETAIL_HEADER_HEIGHT_CLASS, DAY_DETAIL_TIME_LABEL_WIDTH_CLASS, DAY_DETAIL_EVENT_PADDING_CLASS, DAY_DETAIL_EVENT_RADIUS_CLASS, DAY_DETAIL_EVENT_TEXT_CLASS, DAY_DETAIL_SCROLL_AREA_CLASS, DAY_DETAIL_CURRENT_TIME_LINE_CLASS, DAY_DETAIL_CURRENT_TIME_LABEL_CLASS, WEEKDAY_HOURS, WEEKDAY_MINUTES_PER_HOUR, WEEKDAY_HOUR_LABEL_MODE, WEEKDAY_DAY_FORMAT, WEEKDAY_DATE_FORMAT, WEEKDAY_GRID_TIME_COLUMN_Z_INDEX, WEEKDAY_CURRENT_TIME_UPDATE_INTERVAL_MS, WEEKDAY_SECONDS_PER_MINUTE, WEEKDAY_MS_PER_SECOND, WEEKDAY_CSS_VAR_HOUR_ROW_HEIGHT, WEEKDAY_CSS_VAR_EVENT_START_HOUR, WEEKDAY_CSS_VAR_EVENT_DURATION_HOURS, WEEKDAY_CURRENT_TIME_INDICATOR_HEIGHT, WEEKDAY_CURRENT_TIME_DASHED_STYLE, WEEKDAY_HOUR_LABEL_PADDING_RIGHT, WEEKDAY_HOUR_LABEL_FONT_SIZE, WEEKDAY_EVENT_CHIP_PADDING_X };
