// Auto-generated by tools/design-tokens/build-tokens.ts
package com.akari221.flashcardmaster.designsystem.tokens

object DesignTokens {
    object Color {
        object Primary {
            const val Value50 = "#f4f7fb"
            const val Value100 = "#e7eef8"
            const val Value200 = "#cfdbef"
            const val Value300 = "#aabfe0"
            const val Value400 = "#7f9ecb"
            const val Value500 = "#5d7fb6"
            const val Value600 = "#45679d"
            const val Value700 = "#35507b"
            const val Value800 = "#25395a"
            const val Value900 = "#17253d"
        }
        object Neutral {
            const val Value0 = "#ffffff"
            const val Value50 = "#f8fafc"
            const val Value100 = "#f5f5f5"
            const val Value150 = "#f7f7f8"
            const val Value200 = "#e7ebef"
            const val Value300 = "#d9d9d9"
            const val Value400 = "#cfd9e8"
            const val Value500 = "#978d90"
            const val Value600 = "#6e6e80"
            const val Value700 = "#334155"
            const val Value800 = "#1e293b"
            const val Value900 = "#202123"
        }
        object Status {
            const val Danger = "#e11d48"
            const val DangerSoft = "#fef2f2"
            const val Warning = "#f59e0b"
            const val WarningSoft = "#fffbeb"
            const val Success = "#10b981"
            const val SuccessSoft = "#eefdf6"
            const val Info = "#00a3ff"
            const val InfoSoft = "#eff6ff"
        }
        object Code {
            const val Background = "#f7f8f9"
            const val Foreground = "#24292f"
            const val Border = "rgba(0, 0, 0, 0.06)"
        }
        object Tag {
            object Gray {
                const val Bg = "#F1EFE8"
                const val Fg = "#444441"
                const val Border = "transparent"
            }
            object Purple {
                const val Bg = "#EEEDFE"
                const val Fg = "#3C3489"
                const val Border = "transparent"
            }
            object Teal {
                const val Bg = "#E1F5EE"
                const val Fg = "#085041"
                const val Border = "transparent"
            }
            object Pink {
                const val Bg = "#FBEAF0"
                const val Fg = "#72243E"
                const val Border = "transparent"
            }
            object Amber {
                const val Bg = "#FAEEDA"
                const val Fg = "#633806"
                const val Border = "transparent"
            }
            object Blue {
                const val Bg = "#E6F1FB"
                const val Fg = "#0C447C"
                const val Border = "transparent"
            }
            object Green {
                const val Bg = "#EAF3DE"
                const val Fg = "#27500A"
                const val Border = "transparent"
            }
            object Red {
                const val Bg = "#FCEBEB"
                const val Fg = "#791F1F"
                const val Border = "transparent"
            }
            object Coral {
                const val Bg = "#FAECE7"
                const val Fg = "#712B13"
                const val Border = "transparent"
            }
            object Sky {
                const val Bg = "#E1F4FA"
                const val Fg = "#0C4A6E"
                const val Border = "transparent"
            }
        }
    }
    object Spacing {
        const val Value0 = 0
        const val Value1 = 4
        const val Value2 = 8
        const val Value3 = 12
        const val Value4 = 16
        const val Value5 = 20
        const val Value6 = 24
        const val Value8 = 32
        const val Value10 = 40
        const val Value12 = 48
        const val Value16 = 64
        const val Value20 = 80
        const val Value18 = 7.2
    }
    object Radius {
        const val Sm = 8
        const val Md = 10
        const val Lg = 12
        const val Xl = 16
        const val Value2xl = 24
        const val Value3xl = 32
        const val Pill = 999
        const val Floating = 12
    }
    object Typography {
        object FontFamily {
            const val Ui = listOf("Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif")
            const val Content = listOf("Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "MS PMincho", "serif")
            const val Numeric = listOf("Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif")
            const val Code = listOf("Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace")
        }
        object FontSize {
            const val Xs = 12.8
            const val Sm = 14
            const val SmPlus = 14.4
            const val Md = 16
            const val MdPlus = 17.6
            const val Lg = 20
            const val Value2xl = 32
        }
        object LineHeight {
            const val Tight = 1.1
            const val Body = 1.5
            const val Comfortable = 1.625
        }
        object FontWeight {
            const val Medium = 500
            const val Semibold = 600
            const val Bold = 700
            const val Black = 900
        }
        object Tracking {
            const val Caps = 0.12
            const val WideCaps = 0.2
        }
    }
    object Motion {
        object DurationMs {
            const val Instant = 0
            const val Fast = 75
            const val Normal = 150
            const val Moderate = 200
            const val Slow = 300
            const val Toast = 500
            const val Celebration = 700
        }
        object Easing {
            const val Standard = "ease"
            const val Emphasized = "ease-out"
            const val Linear = "linear"
        }
        object Transition {
            const val Interactive = "150ms ease"
            const val ScreenEnter = "300ms ease-out"
            const val Progress = "500ms ease-out"
        }
    }
    object Elevation {
        object Shadow {
            const val Concave = "inset 0 1px 2px rgba(86, 72, 74, 0.16)"
            const val Convex = "0 1px 0 rgba(255, 255, 255, 0.9) inset, 0 -1px 0 rgba(86, 72, 74, 0.08) inset, 0 1px 2px rgba(86, 72, 74, 0.16)"
            const val Floating = "0 8px 24px rgba(15, 23, 42, 0.08)"
            const val Panel = "0 10px 24px rgba(15, 23, 42, 0.12), 0 2px 4px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95), inset 0 -1px 0 rgba(148, 163, 184, 0.25)"
            const val Soft = "0 2px 15px -3px rgba(69, 103, 157, 0.15), 0 10px 20px -2px rgba(69, 103, 157, 0.08)"
            const val Card = "0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 8px -2px rgba(0, 0, 0, 0.04)"
            const val CardHover = "0 8px 30px -4px rgba(69, 103, 157, 0.2), 0 4px 12px -2px rgba(0, 0, 0, 0.08)"
        }
        object Blur {
            const val Floating = 12
        }
    }
    object Layout {
        object Card {
            const val BaseWidth = 480
            const val DisplayMaxHeight = "min(70vh, 560px)"
            const val RowPx = 24
            const val SelectedOutlineWidth = 1.6
        }
        object Tree {
            const val Indent = 12
        }
        object Content {
            const val MaxWidth = 760
        }
        object RowHeight {
            const val Dense = 28
            const val Normal = 32
        }
        object FontSize {
            const val PageTitle = 22
            const val Section = 13
            const val Body = 13
            const val Meta = 12
        }
        object Scrollbar {
            const val Size = 6
        }
    }
    object Semantic {
        object Color {
            object Background {
                const val App = "#ffffff"
                const val Sidebar = "#ececee"
                const val SidebarActive = "#f7f7f8"
                const val Floating = "rgba(255, 255, 255, 0.9)"
                const val Code = "#f7f8f9"
            }
            object Border {
                const val Default = "#d7d9de"
                const val Floating = "rgba(215, 217, 222, 0.82)"
                const val Strong = "#c7cad1"
            }
            object Text {
                const val Primary = "#2f3640"
                const val Secondary = "#6f7681"
                const val Strong = "#202734"
                const val Placeholder = "#939aa4"
                const val OnPrimary = "#ffffff"
            }
            object Action {
                const val Primary = "#3f5f90"
                const val PrimaryHover = "#2f4f83"
                const val PrimarySoft = "#edf2fa"
                const val Accent = "#2f4f83"
            }
            object Interactive {
                const val SelectedSubtle = "#f1f4f8"
                const val SelectedAccent = "#2f4f83"
                const val ColumnSelectedSubtle = "rgba(47, 79, 131, 0.08)"
                const val ColumnSelectedAccent = "#223b62"
            }
            object Status {
                const val Danger = "#e11d48"
                const val Warning = "#f59e0b"
                const val Success = "#10b981"
                const val Info = "#00a3ff"
            }
        }
        object Spacing {
            const val ControlHeight = 36
            const val ControlHeightLarge = 40
            const val PanelWidth = 320
            const val MenuMinWidth = 128
            const val SafeTopOffsetBase = 8
            const val SafeBottomPaddingBase = 80
        }
        object Radius {
            const val Control = 10
            const val Card = 16
            const val Flashcard = 12
            const val Dialog = 12
            const val Panel = 24
            const val Hero = 32
            const val Pill = 999
        }
        object Typography {
            const val Ui = listOf("Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif")
            const val Content = listOf("Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "MS PMincho", "serif")
            const val Numeric = listOf("Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif")
            const val Code = listOf("Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace")
        }
        object Elevation {
            const val ControlInset = "inset 0 1px 2px rgba(86, 72, 74, 0.16)"
            const val ControlRaised = "0 1px 0 rgba(255, 255, 255, 0.9) inset, 0 -1px 0 rgba(86, 72, 74, 0.08) inset, 0 1px 2px rgba(86, 72, 74, 0.16)"
            const val Floating = "0 8px 24px rgba(15, 23, 42, 0.08)"
            const val Panel = "0 10px 24px rgba(15, 23, 42, 0.12), 0 2px 4px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95), inset 0 -1px 0 rgba(148, 163, 184, 0.25)"
            const val Card = "0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 8px -2px rgba(0, 0, 0, 0.04)"
            const val CardHover = "0 8px 30px -4px rgba(69, 103, 157, 0.2), 0 4px 12px -2px rgba(0, 0, 0, 0.08)"
        }
        object Motion {
            const val Interactive = "150ms ease"
            const val ScreenEnter = "300ms ease-out"
            const val Progress = "500ms ease-out"
        }
        object Breadcrumb {
            const val Height = 52
            const val Gap = 12
            const val ItemColor = "#6f7681"
            const val ItemHoverColor = "#202734"
            const val CurrentColor = "#2f3640"
            const val SeparatorColor = "#939aa4"
            const val ItemMaxWidth = "min(46vw, 520px)"
        }
        object Tag {
            const val FontSize = 12
            const val FontWeight = 500
            const val LineHeight = "16px"
            const val PaddingInline = 8
            const val PaddingBlock = 1
            const val Gap = 4
            const val Radius = 20
            const val BorderWidth = 0
            const val RemoveButtonSize = 16
            const val RemoveIconSize = 12
            const val FocusRingWidth = 2
        }
    }
}
