// Auto-generated by tools/design-tokens/build-tokens.ts
package com.akari221.flashcardmaster.designsystem.tokens

object DesignTokens {
    object Color {
        object Primary {
            const val Value50 = "#f7f8ef"
            const val Value100 = "#edf0df"
            const val Value200 = "#dce3c2"
            const val Value300 = "#c3cc99"
            const val Value400 = "#a7b275"
            const val Value500 = "#96a867"
            const val Value600 = "#8a9a5b"
            const val Value700 = "#6d7d48"
            const val Value800 = "#586539"
            const val Value900 = "#374023"
        }
        object Neutral {
            const val Value0 = "#ffffff"
            const val Value50 = "#f8fafc"
            const val Value100 = "#f5f5f5"
            const val Value150 = "#f7f7f8"
            const val Value200 = "#e7ebef"
            const val Value300 = "#d9d9d9"
            const val Value400 = "#cfd9e8"
            const val Value500 = "#978d90"
            const val Value600 = "#6e6e80"
            const val Value700 = "#334155"
            const val Value800 = "#1e293b"
            const val Value900 = "#202123"
        }
        object Status {
            const val Danger = "#e11d48"
            const val DangerSoft = "#fef2f2"
            const val Warning = "#f59e0b"
            const val WarningSoft = "#fffbeb"
            const val Success = "#10b981"
            const val SuccessSoft = "#eefdf6"
            const val Info = "#00a3ff"
            const val InfoSoft = "#eff6ff"
        }
        object Code {
            const val Background = "#f7f8f9"
            const val Foreground = "#24292f"
            const val Border = "rgba(0, 0, 0, 0.06)"
        }
        object Tag {
            object Slate {
                const val Bg = "#f3f4f6"
                const val Fg = "#4b5563"
                const val Border = "#d1d5db"
            }
            object Red {
                const val Bg = "#fef2f2"
                const val Fg = "#b42318"
                const val Border = "#f3b5b5"
            }
            object Orange {
                const val Bg = "#fff7ed"
                const val Fg = "#c2410c"
                const val Border = "#fdba74"
            }
            object Amber {
                const val Bg = "#fffbeb"
                const val Fg = "#b45309"
                const val Border = "#fcd34d"
            }
            object Lime {
                const val Bg = "#f7fee7"
                const val Fg = "#4d7c0f"
                const val Border = "#bef264"
            }
            object Green {
                const val Bg = "#f0fdf4"
                const val Fg = "#15803d"
                const val Border = "#86efac"
            }
            object Teal {
                const val Bg = "#f0fdfa"
                const val Fg = "#0f766e"
                const val Border = "#5eead4"
            }
            object Sky {
                const val Bg = "#f0f9ff"
                const val Fg = "#0369a1"
                const val Border = "#7dd3fc"
            }
            object Blue {
                const val Bg = "#eff6ff"
                const val Fg = "#1d4ed8"
                const val Border = "#93c5fd"
            }
            object Violet {
                const val Bg = "#f5f3ff"
                const val Fg = "#6d28d9"
                const val Border = "#c4b5fd"
            }
        }
    }
    object Spacing {
        const val Value0 = 0
        const val Value1 = 4
        const val Value2 = 8
        const val Value3 = 12
        const val Value4 = 16
        const val Value5 = 20
        const val Value6 = 24
        const val Value8 = 32
        const val Value10 = 40
        const val Value12 = 48
        const val Value16 = 64
        const val Value20 = 80
        const val Value18 = 7.2
    }
    object Radius {
        const val Sm = 8
        const val Md = 10
        const val Lg = 12
        const val Xl = 16
        const val Value2xl = 24
        const val Value3xl = 32
        const val Pill = 999
        const val Floating = 12
    }
    object Typography {
        object FontFamily {
            const val Ui = listOf("Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif")
            const val Content = listOf("Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "MS PMincho", "serif")
            const val Numeric = listOf("Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif")
            const val Code = listOf("Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace")
        }
        object FontSize {
            const val Xs = 12.8
            const val Sm = 14
            const val SmPlus = 14.4
            const val Md = 16
            const val MdPlus = 17.6
            const val Lg = 20
            const val Value2xl = 32
        }
        object LineHeight {
            const val Tight = 1.1
            const val Body = 1.5
            const val Comfortable = 1.625
        }
        object FontWeight {
            const val Medium = 500
            const val Semibold = 600
            const val Bold = 700
            const val Black = 900
        }
        object Tracking {
            const val Caps = 0.12
            const val WideCaps = 0.2
        }
    }
    object Motion {
        object DurationMs {
            const val Instant = 0
            const val Fast = 75
            const val Normal = 150
            const val Moderate = 200
            const val Slow = 300
            const val Toast = 500
            const val Celebration = 700
        }
        object Easing {
            const val Standard = "ease"
            const val Emphasized = "ease-out"
            const val Linear = "linear"
        }
        object Transition {
            const val Interactive = "150ms ease"
            const val ScreenEnter = "300ms ease-out"
            const val Progress = "500ms ease-out"
        }
    }
    object Elevation {
        object Shadow {
            const val Concave = "inset 0 1px 2px rgba(86, 72, 74, 0.16)"
            const val Convex = "0 1px 0 rgba(255, 255, 255, 0.9) inset, 0 -1px 0 rgba(86, 72, 74, 0.08) inset, 0 1px 2px rgba(86, 72, 74, 0.16)"
            const val Floating = "0 8px 24px rgba(15, 23, 42, 0.08)"
            const val Panel = "0 10px 24px rgba(15, 23, 42, 0.12), 0 2px 4px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95), inset 0 -1px 0 rgba(148, 163, 184, 0.25)"
            const val Soft = "0 2px 15px -3px rgba(104, 154, 152, 0.15), 0 10px 20px -2px rgba(104, 154, 152, 0.08)"
            const val Card = "0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 8px -2px rgba(0, 0, 0, 0.04)"
            const val CardHover = "0 8px 30px -4px rgba(104, 154, 152, 0.2), 0 4px 12px -2px rgba(0, 0, 0, 0.08)"
        }
        object Blur {
            const val Floating = 12
        }
    }
    object Layout {
        object Card {
            const val BaseWidth = 480
            const val DisplayMaxHeight = "min(70vh, 560px)"
            const val RowPx = 24
            const val SelectedOutlineWidth = 1.6
        }
        object Tree {
            const val Indent = 12
        }
        object Content {
            const val MaxWidth = 760
        }
        object RowHeight {
            const val Dense = 28
            const val Normal = 32
        }
        object FontSize {
            const val PageTitle = 22
            const val Section = 13
            const val Body = 13
            const val Meta = 12
        }
        object Scrollbar {
            const val Size = 6
        }
    }
    object Semantic {
        object Color {
            object Background {
                const val App = "#ffffff"
                const val Sidebar = "#f6f1eb"
                const val SidebarActive = "#ece2d7"
                const val Floating = "rgba(255, 255, 255, 0.82)"
                const val Code = "#f7f8f9"
            }
            object Border {
                const val Default = "#d9d9d9"
                const val Floating = "rgba(226, 232, 240, 0.8)"
                const val Strong = "#cfd9e8"
            }
            object Text {
                const val Primary = "#202123"
                const val Secondary = "#6e6e80"
                const val Strong = "#1e293b"
                const val Placeholder = "#978d90"
                const val OnPrimary = "#ffffff"
            }
            object Action {
                const val Primary = "#8a9a5b"
                const val PrimaryHover = "#6d7d48"
                const val PrimarySoft = "#edf0df"
                const val Accent = "#96a867"
            }
            object Status {
                const val Danger = "#e11d48"
                const val Warning = "#f59e0b"
                const val Success = "#10b981"
                const val Info = "#00a3ff"
            }
        }
        object Spacing {
            const val ControlHeight = 36
            const val ControlHeightLarge = 40
            const val PanelWidth = 320
            const val MenuMinWidth = 128
            const val SafeTopOffsetBase = 8
            const val SafeBottomPaddingBase = 80
        }
        object Radius {
            const val Control = 10
            const val Card = 16
            const val Flashcard = 12
            const val Dialog = 12
            const val Panel = 24
            const val Hero = 32
            const val Pill = 999
        }
        object Typography {
            const val Ui = listOf("Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif")
            const val Content = listOf("Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "MS PMincho", "serif")
            const val Numeric = listOf("Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif")
            const val Code = listOf("Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace")
        }
        object Elevation {
            const val ControlInset = "inset 0 1px 2px rgba(86, 72, 74, 0.16)"
            const val ControlRaised = "0 1px 0 rgba(255, 255, 255, 0.9) inset, 0 -1px 0 rgba(86, 72, 74, 0.08) inset, 0 1px 2px rgba(86, 72, 74, 0.16)"
            const val Floating = "0 8px 24px rgba(15, 23, 42, 0.08)"
            const val Panel = "0 10px 24px rgba(15, 23, 42, 0.12), 0 2px 4px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95), inset 0 -1px 0 rgba(148, 163, 184, 0.25)"
            const val Card = "0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 8px -2px rgba(0, 0, 0, 0.04)"
            const val CardHover = "0 8px 30px -4px rgba(104, 154, 152, 0.2), 0 4px 12px -2px rgba(0, 0, 0, 0.08)"
        }
        object Motion {
            const val Interactive = "150ms ease"
            const val ScreenEnter = "300ms ease-out"
            const val Progress = "500ms ease-out"
        }
    }
}
