import {
  CARD_PANE_AUTO_MAX_SCALE,
  CARD_PANE_EDIT_DEFAULT_WIDTH_PX,
  CARD_PANE_EDIT_MIN_WIDTH_PX,
  CARD_PANE_VIEW_DEFAULT_WIDTH_PX,
  CARD_PANE_VIEW_MIN_WIDTH_PX,
  CARD_PANE_WIDTH_CONTROL_CLEARANCE_PX,
  CARD_PANE_WIDTH_STEP_PX,
  clampPaneWidthPx,
} from "@/components/card/shell/cardPaneWidthConstants";

export const CARDVIEW_PAGER_PADDING_INLINE = 0;
export const CARDVIEW_PAGER_PADDING_BLOCK = "50vh";
export const CARDVIEW_NATURAL_INDEX_COMMIT_DELAY_VIEW_MS = 0;
export const CARDVIEW_NATURAL_INDEX_COMMIT_DELAY_EDIT_MS = 0;
export const CARDVIEW_SAVE_FINISHED_EVENT = "cardview:save-finished";

export {
  CARD_PANE_AUTO_MAX_SCALE,
  CARD_PANE_EDIT_DEFAULT_WIDTH_PX,
  CARD_PANE_EDIT_MIN_WIDTH_PX,
  CARD_PANE_VIEW_DEFAULT_WIDTH_PX,
  CARD_PANE_VIEW_MIN_WIDTH_PX,
  CARD_PANE_WIDTH_CONTROL_CLEARANCE_PX,
  CARD_PANE_WIDTH_STEP_PX,
  clampPaneWidthPx,
};