// Auto-generated by tools/design-tokens/build-tokens.ts
export const designTokens = {
  "color": {
    "primary": {
      "50": "#f4f8f5",
      "100": "#e2ede4",
      "200": "#c6d9ca",
      "300": "#9cbba5",
      "400": "#6f997e",
      "500": "#477a5d",
      "600": "#2d5e41",
      "700": "#245138",
      "800": "#1f4a36",
      "900": "#1b4332"
    },
    "neutral": {
      "0": "#ffffff",
      "50": "#f8fafc",
      "100": "#f5f5f5",
      "150": "#f7f7f8",
      "200": "#e7ebef",
      "300": "#d9d9d9",
      "400": "#cfd9e8",
      "500": "#978d90",
      "600": "#6e6e80",
      "700": "#334155",
      "800": "#1e293b",
      "900": "#202123"
    },
    "status": {
      "danger": "#e11d48",
      "dangerSoft": "#fef2f2",
      "warning": "#f59e0b",
      "warningSoft": "#fffbeb",
      "success": "#10b981",
      "successSoft": "#eefdf6",
      "info": "#00a3ff",
      "infoSoft": "#eff6ff"
    },
    "code": {
      "background": "#f7f8f9",
      "foreground": "#24292f",
      "border": "rgba(0, 0, 0, 0.06)"
    },
    "tag": {
      "slate": {
        "bg": "#f1f5f9",
        "fg": "#1e293b",
        "border": "#e2e8f0"
      },
      "red": {
        "bg": "#fee2e2",
        "fg": "#991b1b",
        "border": "#fecaca"
      },
      "orange": {
        "bg": "#ffedd5",
        "fg": "#9a3412",
        "border": "#fed7aa"
      },
      "amber": {
        "bg": "#fef3c7",
        "fg": "#92400e",
        "border": "#fde68a"
      },
      "lime": {
        "bg": "#ecfccb",
        "fg": "#3f6212",
        "border": "#d9f99d"
      },
      "green": {
        "bg": "#dcfce7",
        "fg": "#166534",
        "border": "#bbf7d0"
      },
      "emerald": {
        "bg": "#d1fae5",
        "fg": "#065f46",
        "border": "#a7f3d0"
      },
      "teal": {
        "bg": "#ccfbf1",
        "fg": "#115e59",
        "border": "#99f6e4"
      },
      "cyan": {
        "bg": "#cffafe",
        "fg": "#155e75",
        "border": "#a5f3fc"
      },
      "sky": {
        "bg": "#e0f2fe",
        "fg": "#075985",
        "border": "#bae6fd"
      },
      "blue": {
        "bg": "#dbeafe",
        "fg": "#1e40af",
        "border": "#bfdbfe"
      },
      "indigo": {
        "bg": "#e0e7ff",
        "fg": "#3730a3",
        "border": "#c7d2fe"
      },
      "violet": {
        "bg": "#ede9fe",
        "fg": "#5b21b6",
        "border": "#ddd6fe"
      },
      "purple": {
        "bg": "#f3e8ff",
        "fg": "#6b21a8",
        "border": "#e9d5ff"
      },
      "fuchsia": {
        "bg": "#fae8ff",
        "fg": "#86198f",
        "border": "#f5d0fe"
      },
      "pink": {
        "bg": "#fce7f3",
        "fg": "#9d174d",
        "border": "#fbcfe8"
      },
      "rose": {
        "bg": "#ffe4e6",
        "fg": "#9f1239",
        "border": "#fecdd3"
      }
    }
  },
  "spacing": {
    "0": 0,
    "1": 4,
    "1_8": 7.2,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64,
    "20": 80
  },
  "radius": {
    "sm": 8,
    "md": 10,
    "lg": 12,
    "xl": 16,
    "2xl": 24,
    "3xl": 32,
    "pill": 999,
    "floating": 12
  },
  "typography": {
    "fontFamily": {
      "ui": ["Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      "content": ["Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "MS PMincho", "serif"],
      "numeric": ["Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      "code": ["Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"]
    },
    "fontSize": {
      "xs": 12.8,
      "sm": 14,
      "smPlus": 14.4,
      "md": 16,
      "mdPlus": 17.6,
      "lg": 20,
      "2xl": 32
    },
    "lineHeight": {
      "tight": 1.1,
      "body": 1.5,
      "comfortable": 1.625
    },
    "fontWeight": {
      "medium": 500,
      "semibold": 600,
      "bold": 700,
      "black": 900
    },
    "tracking": {
      "caps": 0.12,
      "wideCaps": 0.2
    }
  },
  "motion": {
    "durationMs": {
      "instant": 0,
      "fast": 75,
      "normal": 150,
      "moderate": 200,
      "slow": 300,
      "toast": 500,
      "celebration": 700
    },
    "easing": {
      "standard": "ease",
      "emphasized": "ease-out",
      "linear": "linear"
    },
    "transition": {
      "interactive": "150ms ease",
      "screenEnter": "300ms ease-out",
      "progress": "500ms ease-out"
    }
  },
  "elevation": {
    "shadow": {
      "concave": "inset 0 1px 2px rgba(86, 72, 74, 0.16)",
      "convex": "0 1px 0 rgba(255, 255, 255, 0.9) inset, 0 -1px 0 rgba(86, 72, 74, 0.08) inset, 0 1px 2px rgba(86, 72, 74, 0.16)",
      "floating": "0 8px 24px rgba(15, 23, 42, 0.08)",
      "panel": "0 10px 24px rgba(15, 23, 42, 0.12), 0 2px 4px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95), inset 0 -1px 0 rgba(148, 163, 184, 0.25)",
      "soft": "0 2px 15px -3px rgba(104, 154, 152, 0.15), 0 10px 20px -2px rgba(104, 154, 152, 0.08)",
      "card": "0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 8px -2px rgba(0, 0, 0, 0.04)",
      "cardHover": "0 8px 30px -4px rgba(104, 154, 152, 0.2), 0 4px 12px -2px rgba(0, 0, 0, 0.08)"
    },
    "blur": {
      "floating": 12
    }
  },
  "layout": {
    "card": {
      "baseWidth": 480,
      "displayMaxHeight": "min(70vh, 560px)",
      "rowPx": 24,
      "selectedOutlineWidth": 1.6
    },
    "tree": {
      "indent": 12
    },
    "content": {
      "maxWidth": 760
    },
    "rowHeight": {
      "dense": 28,
      "normal": 32
    },
    "fontSize": {
      "pageTitle": 22,
      "section": 13,
      "body": 13,
      "meta": 12
    },
    "scrollbar": {
      "size": 6
    },
    "shell": {
      "sidebarWidth": 220,
      "detailPanelWidth": 220
    }
  },
  "semantic": {
    "color": {
      "background": {
        "app": "#ffffff",
        "sidebar": "#f5f4ef",
        "sidebarActive": "#e2ede4",
        "floating": "rgba(255, 255, 255, 0.82)",
        "code": "#f7f8f9"
      },
      "border": {
        "default": "#d8e2da",
        "floating": "rgba(216, 226, 218, 0.8)",
        "strong": "#b8cec0"
      },
      "text": {
        "primary": "#202123",
        "secondary": "#6e6e80",
        "strong": "#1b4332",
        "placeholder": "#978d90",
        "onPrimary": "#ffffff"
      },
      "action": {
        "primary": "#2d5e41",
        "primaryHover": "#1b4332",
        "primarySoft": "#e2ede4",
        "accent": "#477a5d"
      },
      "status": {
        "danger": "#e11d48",
        "warning": "#f59e0b",
        "success": "#10b981",
        "info": "#00a3ff"
      }
    },
    "spacing": {
      "controlHeight": 36,
      "controlHeightLarge": 40,
      "panelWidth": 320,
      "menuMinWidth": 128,
      "safeTopOffsetBase": 8,
      "safeBottomPaddingBase": 80
    },
    "radius": {
      "control": 10,
      "card": 16,
      "flashcard": 12,
      "dialog": 12,
      "panel": 24,
      "hero": 32,
      "pill": 999
    },
    "typography": {
      "ui": ["Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      "content": ["Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "MS PMincho", "serif"],
      "numeric": ["Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      "code": ["Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"]
    },
    "elevation": {
      "controlInset": "inset 0 1px 2px rgba(86, 72, 74, 0.16)",
      "controlRaised": "0 1px 0 rgba(255, 255, 255, 0.9) inset, 0 -1px 0 rgba(86, 72, 74, 0.08) inset, 0 1px 2px rgba(86, 72, 74, 0.16)",
      "floating": "0 8px 24px rgba(15, 23, 42, 0.08)",
      "panel": "0 10px 24px rgba(15, 23, 42, 0.12), 0 2px 4px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95), inset 0 -1px 0 rgba(148, 163, 184, 0.25)",
      "card": "0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 8px -2px rgba(0, 0, 0, 0.04)",
      "cardHover": "0 8px 30px -4px rgba(104, 154, 152, 0.2), 0 4px 12px -2px rgba(0, 0, 0, 0.08)"
    },
    "motion": {
      "interactive": "150ms ease",
      "screenEnter": "300ms ease-out",
      "progress": "500ms ease-out"
    }
  }
} as const;

export const reactThemeContract = {
  cssFile: "./design-tokens.css",
  cssVariablePrefix: "--ds-",
  rootSelector: ":root",
} as const;
