//
export const CALENDAR_WEEKDAY_HEADER_HEIGHT = 32;
export const WEEKDAY_HEADER_HEIGHT_PX = CALENDAR_WEEKDAY_HEADER_HEIGHT;
export const CALENDAR_DAY_HEADER_CELL_HEIGHT = 112;

export const INITIAL_MONTH_BUFFER = 12;
export const MONTH_EXTEND_COUNT = 6;
export const MONTH_MAX_RENDERED_MONTHS = 36;
export const MONTH_VIEW_EVENT_RANGE_BUFFER_DAYS = 7;

export const MONTH_SCROLL_EDGE_THRESHOLD_PX = 2400;
export const MONTH_SCROLL_VISIBLE_SAMPLE_OFFSET_PX = 56;

export const DEFAULT_MONTH_ROW_HEIGHT = CALENDAR_DAY_HEADER_CELL_HEIGHT;

export const createInitialMonthOffsetRange = () => ({
  startOffset: -INITIAL_MONTH_BUFFER,
  endOffset: INITIAL_MONTH_BUFFER,
});

//Timeline View
export const TIMELINE_HEADER_HEIGHT = 40;

export const TIMELINE_DEFAULT_ROW_HEIGHT = 168;

export const TIMELINE_DEFAULT_LANE_LABEL_WIDTH = 168;
export const TIMELINE_DEFAULT_ROW_COUNT = 4;

//Side Calendar
export const WEEK_STARTS_ON_MONDAY = 1;
export const TIME_COLUMN_WIDTH = 50;
export const DAY_COLUMN_MIN_WIDTH = 136;
export const DEFAULT_HOUR_ROW_HEIGHT = 80;
export const INITIAL_CALENDAR_BUFFER_DAYS = 7;
export const CALENDAR_EXTEND_DAYS = 14;
export const TIMELINE_EDGE_THRESHOLD_PX = 1800;
export const TIMELINE_DAY_COLUMN_WIDTH = 104;
export const TIMELINE_LANE_LABEL_WIDTH = 168;
export const TIMELINE_SKELETON_ROW_COUNT = 4;
export const MINI_CALENDAR_CELL_COUNT = 42;
export const WEEKDAY_SURFACE_LEFT_INSET_PX = 16;

//
export const MIN_EVENT_DISPLAY_HEIGHT_PX = 48; // min-h-12 に対応
export const MIN_LAYOUT_MINUTES = Math.ceil(
  (MIN_EVENT_DISPLAY_HEIGHT_PX / DEFAULT_HOUR_ROW_HEIGHT) * 60,
);
