//
const CALENDAR_WEEKDAY_HEADER_HEIGHT = 32;
const WEEKDAY_HEADER_HEIGHT_PX = CALENDAR_WEEKDAY_HEADER_HEIGHT;
const CALENDAR_DAY_HEADER_CELL_HEIGHT = 112;
const INITIAL_MONTH_BUFFER = 12;
const MONTH_EXTEND_COUNT = 6;
const MONTH_MAX_RENDERED_MONTHS = 36;
const MONTH_VIEW_EVENT_RANGE_BUFFER_DAYS = 7;
const MONTH_SCROLL_EDGE_THRESHOLD_PX = 2400;
const MONTH_SCROLL_VISIBLE_SAMPLE_OFFSET_PX = 56;
const DEFAULT_MONTH_ROW_HEIGHT = CALENDAR_DAY_HEADER_CELL_HEIGHT;
const MONTH_VISIBLE_EVENT_COUNT_MIN = 1;
const DEFAULT_MONTH_VISIBLE_EVENT_COUNT = 3;
const MONTH_VISIBLE_EVENT_COUNT_MAX = 20;
//Timeline View
const TIMELINE_HEADER_HEIGHT = 40;
const TIMELINE_DEFAULT_ROW_HEIGHT = 168;
const TIMELINE_DEFAULT_LANE_LABEL_WIDTH = 168;
const TIMELINE_DEFAULT_ROW_COUNT = 4;
//Side Calendar
const WEEK_STARTS_ON_MONDAY = 1;
const TIME_COLUMN_WIDTH = 52;
const DAY_COLUMN_MIN_WIDTH = 136;
const DEFAULT_HOUR_ROW_HEIGHT = 80;
const INITIAL_CALENDAR_BUFFER_DAYS = 7;
const CALENDAR_EXTEND_DAYS = 14;
const TIMELINE_EDGE_THRESHOLD_PX = 1800;
const TIMELINE_DAY_COLUMN_WIDTH = 104;
const TIMELINE_LANE_LABEL_WIDTH = 168;
const TIMELINE_SKELETON_ROW_COUNT = 4;
const WEEKDAY_SURFACE_LEFT_INSET_PX = 16;
//
const MIN_EVENT_DISPLAY_HEIGHT_PX = 48;
// min-h-12 に対応
const MIN_LAYOUT_MINUTES = Math.ceil((MIN_EVENT_DISPLAY_HEIGHT_PX / DEFAULT_HOUR_ROW_HEIGHT) * 60);



const createInitialMonthOffsetRange = () => ({ startOffset: -INITIAL_MONTH_BUFFER, endOffset: INITIAL_MONTH_BUFFER });



export { CALENDAR_WEEKDAY_HEADER_HEIGHT, WEEKDAY_HEADER_HEIGHT_PX, CALENDAR_DAY_HEADER_CELL_HEIGHT, INITIAL_MONTH_BUFFER, MONTH_EXTEND_COUNT, MONTH_MAX_RENDERED_MONTHS, MONTH_VIEW_EVENT_RANGE_BUFFER_DAYS, MONTH_SCROLL_EDGE_THRESHOLD_PX, MONTH_SCROLL_VISIBLE_SAMPLE_OFFSET_PX, DEFAULT_MONTH_ROW_HEIGHT, MONTH_VISIBLE_EVENT_COUNT_MIN, DEFAULT_MONTH_VISIBLE_EVENT_COUNT, MONTH_VISIBLE_EVENT_COUNT_MAX, createInitialMonthOffsetRange, TIMELINE_HEADER_HEIGHT, TIMELINE_DEFAULT_ROW_HEIGHT, TIMELINE_DEFAULT_LANE_LABEL_WIDTH, TIMELINE_DEFAULT_ROW_COUNT, WEEK_STARTS_ON_MONDAY, TIME_COLUMN_WIDTH, DAY_COLUMN_MIN_WIDTH, DEFAULT_HOUR_ROW_HEIGHT, INITIAL_CALENDAR_BUFFER_DAYS, CALENDAR_EXTEND_DAYS, TIMELINE_EDGE_THRESHOLD_PX, TIMELINE_DAY_COLUMN_WIDTH, TIMELINE_LANE_LABEL_WIDTH, TIMELINE_SKELETON_ROW_COUNT, WEEKDAY_SURFACE_LEFT_INSET_PX, MIN_EVENT_DISPLAY_HEIGHT_PX, MIN_LAYOUT_MINUTES };
