import { CARD_PANE_AUTO_MAX_SCALE, CARD_PANE_EDIT_DEFAULT_WIDTH_PX, CARD_PANE_EDIT_MIN_WIDTH_PX, CARD_PANE_VIEW_DEFAULT_WIDTH_PX, CARD_PANE_VIEW_MIN_WIDTH_PX, CARD_PANE_WIDTH_STEP_PX } from "@/components/card/frame/cardPane.constants";
import { CANONICAL_CARD_WIDTH } from "@/domain/card/cardGeometry.constants";



type CardViewZoomInteractionSource = "slider" | "button" | "wheel" | "gesture";



const CARD_SET_VIEW_PAGER_PADDING_INLINE = 0;
const CARD_SET_VIEW_PAGER_PADDING_BLOCK = "50vh";
const CARD_SET_VIEW_NATURAL_INDEX_COMMIT_DELAY_VIEW_MS = 0;
const CARD_SET_VIEW_NATURAL_INDEX_COMMIT_DELAY_EDIT_MS = 0;
const CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE = {
  slider: 1,
  button: 5,
  wheel: 1,
  gesture: 1,
} as const satisfies Record<CardViewZoomInteractionSource, number>;
const CARD_VIEW_ZOOM_SLIDER_STEP_PERCENT = CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE.slider;
const CARD_VIEW_ZOOM_BUTTON_STEP_PERCENT = CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE.button;
const CARD_VIEW_ZOOM_WHEEL_STEP_PERCENT = CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE.wheel;
const CARD_VIEW_ZOOM_GESTURE_STEP_PERCENT = CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE.gesture;
const CARD_VIEW_ZOOM_STEP_PERCENT = CARD_VIEW_ZOOM_BUTTON_STEP_PERCENT;
const CARD_VIEW_ZOOM_DEFAULT_PERCENT = Math.round((CARD_PANE_VIEW_DEFAULT_WIDTH_PX / CANONICAL_CARD_WIDTH) * 100);
const CARD_VIEW_ZOOM_MIN_PERCENT = Math.round((CARD_PANE_VIEW_MIN_WIDTH_PX / CANONICAL_CARD_WIDTH) * 100);
const CARD_VIEW_DEFAULT_ZOOM_PERCENT = CARD_VIEW_ZOOM_DEFAULT_PERCENT;
const CARD_VIEW_MIN_ZOOM_PERCENT = CARD_VIEW_ZOOM_MIN_PERCENT;



export { CARD_PANE_AUTO_MAX_SCALE, CARD_PANE_EDIT_DEFAULT_WIDTH_PX, CARD_PANE_EDIT_MIN_WIDTH_PX, CARD_PANE_VIEW_DEFAULT_WIDTH_PX, CARD_PANE_VIEW_MIN_WIDTH_PX, CARD_PANE_WIDTH_STEP_PX, CARD_SET_VIEW_NATURAL_INDEX_COMMIT_DELAY_EDIT_MS, CARD_SET_VIEW_NATURAL_INDEX_COMMIT_DELAY_VIEW_MS, CARD_SET_VIEW_PAGER_PADDING_BLOCK, CARD_SET_VIEW_PAGER_PADDING_INLINE, CARD_VIEW_DEFAULT_ZOOM_PERCENT, CARD_VIEW_MIN_ZOOM_PERCENT, CARD_VIEW_ZOOM_BUTTON_STEP_PERCENT, CARD_VIEW_ZOOM_DEFAULT_PERCENT, CARD_VIEW_ZOOM_GESTURE_STEP_PERCENT, CARD_VIEW_ZOOM_MIN_PERCENT, CARD_VIEW_ZOOM_SLIDER_STEP_PERCENT, CARD_VIEW_ZOOM_STEP_PERCENT, CARD_VIEW_ZOOM_STEP_PERCENT_BY_SOURCE, CARD_VIEW_ZOOM_WHEEL_STEP_PERCENT };


export type { CardViewZoomInteractionSource };
