type TrashEntityBase = {
  [key: string]: unknown;
  id: string;
  isDeleted?: boolean;
  deletedAt?: unknown;
};
type TrashFolderBase = TrashEntityBase & { parentFolderId?: string | null;
};
type TrashCardBase = TrashEntityBase;
type TrashCardSetBase = TrashEntityBase;
type TrashDocumentBase = TrashEntityBase;
type TrashItems<TFolder extends TrashFolderBase = TrashFolderBase, TCard extends TrashCardBase = TrashCardBase, TCardSet extends TrashCardSetBase = TrashCardSetBase, TDocument extends TrashDocumentBase = TrashDocumentBase> = { folders: TFolder[];
  cards: TCard[];
  cardSets: TCardSet[];
  documents: TDocument[];
};
type TrashContext<TFolder extends TrashFolderBase = TrashFolderBase, TCard extends TrashCardBase = TrashCardBase, TCardSet extends TrashCardSetBase = TrashCardSetBase, TDocument extends TrashDocumentBase = TrashDocumentBase> = { folders: TFolder[];
  cards: TCard[];
  cardSets: TCardSet[];
  documents: TDocument[];
  resolveCardFolderId: (card: TCard) => string | null | undefined;
};
type TrashItemIds = {
  folderIds?: string[];
  cardIds?: string[];
  cardSetIds?: string[];
  documentIds?: string[];
};
type TrashRepository<TFolder extends TrashFolderBase = TrashFolderBase, TCard extends TrashCardBase = TrashCardBase, TCardSet extends TrashCardSetBase = TrashCardSetBase, TDocument extends TrashDocumentBase = TrashDocumentBase> = { loadContext: (userId: string) => Promise<TrashContext<TFolder, TCard, TCardSet, TDocument>>;
  restoreFolder: (userId: string, folderId: string) => Promise<void>;
  restoreCard: (userId: string, cardId: string) => Promise<void>;
  restoreCardSet: (userId: string, cardSetId: string) => Promise<void>;
  restoreDocument: (userId: string, documentId: string) => Promise<void>;
  purgeFolder: (userId: string, folderId: string) => Promise<void>;
  purgeCard: (userId: string, cardId: string) => Promise<void>;
  purgeCardSet: (userId: string, cardSetId: string) => Promise<void>;
  purgeDocument: (userId: string, documentId: string) => Promise<void>;
};
type TrashUseCaseInput<TFolder extends TrashFolderBase = TrashFolderBase, TCard extends TrashCardBase = TrashCardBase, TCardSet extends TrashCardSetBase = TrashCardSetBase, TDocument extends TrashDocumentBase = TrashDocumentBase> = { userId: string;
  repository: TrashRepository<TFolder, TCard, TCardSet, TDocument>;
};

export type { TrashEntityBase, TrashFolderBase, TrashCardBase, TrashCardSetBase, TrashDocumentBase, TrashItems, TrashContext, TrashItemIds, TrashRepository, TrashUseCaseInput };
