const LAYERED_TREE_ROOT_LEVEL = 1;
const LAYERED_TREE_INDENT_PX = 14;
const LAYERED_TREE_DROP_INDICATOR_BASE_LEFT_PX = 18;
const LAYERED_TREE_ROOT_DROP_INDICATOR_LEFT_PX = 8;
const LAYERED_TREE_DND_MIME_TYPE = "application/x-sivflow-layered-tree-id";
const LAYERED_TREE_ROW_SELECTOR = "[data-layered-tree-row='true']";
const LAYERED_TREE_FOLDER_ID_ATTRIBUTE = "data-folder-id";
const LAYERED_TREE_TAG_ID_ATTRIBUTE = "data-tag-id";
const LAYERED_TREE_DROP_EDGE_RATIO = 0.24;
const LAYERED_TREE_DROP_INSIDE_INTENT_OFFSET_PX = 76;
const LAYERED_TREE_DROP_HIT_TEST_VERTICAL_TOLERANCE_PX = 8;
const LAYERED_TREE_AUTO_EXPAND_DELAY_MS = 520;
const LAYERED_TREE_DRAG_IMAGE_OFFSET_X = 18;
const LAYERED_TREE_DRAG_IMAGE_OFFSET_Y = 16;
const LAYERED_TREE_AUTO_SCROLL_EDGE_PX = 42;
const LAYERED_TREE_AUTO_SCROLL_MAX_STEP = 18;



export { LAYERED_TREE_ROOT_LEVEL, LAYERED_TREE_INDENT_PX, LAYERED_TREE_DROP_INDICATOR_BASE_LEFT_PX, LAYERED_TREE_ROOT_DROP_INDICATOR_LEFT_PX, LAYERED_TREE_DND_MIME_TYPE, LAYERED_TREE_ROW_SELECTOR, LAYERED_TREE_FOLDER_ID_ATTRIBUTE, LAYERED_TREE_TAG_ID_ATTRIBUTE, LAYERED_TREE_DROP_EDGE_RATIO, LAYERED_TREE_DROP_INSIDE_INTENT_OFFSET_PX, LAYERED_TREE_DROP_HIT_TEST_VERTICAL_TOLERANCE_PX, LAYERED_TREE_AUTO_EXPAND_DELAY_MS, LAYERED_TREE_DRAG_IMAGE_OFFSET_X, LAYERED_TREE_DRAG_IMAGE_OFFSET_Y, LAYERED_TREE_AUTO_SCROLL_EDGE_PX, LAYERED_TREE_AUTO_SCROLL_MAX_STEP };
