type TokenBundle = Record<string, unknown>;

type CssVariableEntry = { name: string; value: string; path: string[] };

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const toKebabCase = (value: string) =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();

const escapeFontFamily = (value: string) =>
  /\s/.test(value) ? `"${value.replaceAll('"', '\\"')}"` : value;

const unitlessNumberPatterns = [/^typography\.(lineHeight|fontWeight)\./];

const millisecondNumberPatterns = [/^motion\.durationMs\./];

const hexColorPattern = /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;

const serializeCssScalar = (value: number, path: string[]) => {
  const tokenPath = path.join(".");

  if (unitlessNumberPatterns.some((pattern) => pattern.test(tokenPath))) {
    return String(value);
  }

  if (millisecondNumberPatterns.some((pattern) => pattern.test(tokenPath))) {
    return `${value}ms`;
  }

  return `${value}px`;
};

const hexToRgbChannels = (value: string) => {
  if (!hexColorPattern.test(value)) {
    return null;
  }

  const normalized =
    value.length === 4
      ? `#${value[1]}${value[1]}${value[2]}${value[2]}${value[3]}${value[3]}`
      : value;

  const red = Number.parseInt(normalized.slice(1, 3), 16);
  const green = Number.parseInt(normalized.slice(3, 5), 16);
  const blue = Number.parseInt(normalized.slice(5, 7), 16);

  return `${red} ${green} ${blue}`;
};

const flattenCssVariables = (
  value: unknown,
  path: string[] = [],
  output: CssVariableEntry[] = [],
) => {
  if (Array.isArray(value)) {
    output.push({
      name: path.map(toKebabCase).join("-"),
      value: value.map((entry) => escapeFontFamily(String(entry))).join(", "),
      path,
    });
    return output;
  }

  if (isRecord(value)) {
    for (const [key, entry] of Object.entries(value)) {
      flattenCssVariables(entry, [...path, key], output);
    }
    return output;
  }

  const normalized =
    typeof value === "number" ? serializeCssScalar(value, path) : String(value);

  output.push({
    name: path.map(toKebabCase).join("-"),
    value: normalized,
    path,
  });

  return output;
};

const addDerivedColorChannels = (entries: CssVariableEntry[]) =>
  entries.flatMap((entry) => {
    const rgbChannels = hexToRgbChannels(entry.value);
    if (rgbChannels === null) {
      return [entry];
    }

    return [
      entry,
      {
        name: `${entry.name}-rgb`,
        value: rgbChannels,
        path: [...entry.path, "rgb"],
      },
    ];
  });

const serializeTsObject = (value: unknown, indent = 0): string => {
  const spacing = "  ".repeat(indent);
  const childSpacing = "  ".repeat(indent + 1);

  if (Array.isArray(value)) {
    return `[${value.map((entry) => serializeTsObject(entry, indent)).join(", ")}]`;
  }

  if (isRecord(value)) {
    const entries = Object.entries(value).map(
      ([key, entry]) =>
        `${childSpacing}${JSON.stringify(key)}: ${serializeTsObject(entry, indent + 1)}`,
    );
    return `{\n${entries.join(",\n")}\n${spacing}}`;
  }

  return JSON.stringify(value);
};

export interface ReactThemeOutput {
  css: string;
  ts: string;
  index: string;
}

export const generateReactTheme = (tokens: TokenBundle): ReactThemeOutput => {
  const cssVariables = addDerivedColorChannels(
    flattenCssVariables(tokens),
  ).sort((left, right) => left.name.localeCompare(right.name));

  const css = [
    "/* Auto-generated by tools/design-tokens/build-tokens.ts */",
    ":root {",
    ...cssVariables.map(({ name, value }) => `  --ds-${name}: ${value};`),
    "}",
    "",
  ].join("\n");

  const ts = [
    "// Auto-generated by tools/design-tokens/build-tokens.ts",
    `export const designTokens = ${serializeTsObject(tokens)} as const;`,
    "",
    "export const reactThemeContract = {",
    '  cssFile: "./design-tokens.css",',
    '  cssVariablePrefix: "--ds-",',
    '  rootSelector: ":root",',
    "} as const;",
    "",
  ].join("\n");

  const index = [
    'export { designTokens, reactThemeContract } from "./design-tokens";',
    "",
  ].join("\n");

  return { css, ts, index };
};
