type TokenBundle = Record<string, unknown>;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const toPascalCase = (value: string) =>
  value
    .replace(/(^|[_\-.])(\w)/g, (_, __, character: string) =>
      character.toUpperCase(),
    )
    .replace(/[^a-zA-Z0-9]/g, "");

const toKtIdentifier = (value: string) => {
  const normalized = toPascalCase(value);
  return /^[0-9]/.test(normalized) ? `Value${normalized}` : normalized;
};

const toKtLiteral = (value: unknown): string => {
  if (Array.isArray(value)) {
    return `listOf(${value.map((entry) => toKtLiteral(entry)).join(", ")})`;
  }

  if (typeof value === "number") {
    return Number.isInteger(value) ? `${value}` : `${value}`;
  }

  return `"${String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
};

const buildKtSections = (value: unknown, name: string, indent = 1): string => {
  const spacing = "    ".repeat(indent);

  if (!isRecord(value)) {
    return `${spacing}const val ${name} = ${toKtLiteral(value)}`;
  }

  const entries = Object.entries(value).map(([key, entry]) =>
    buildKtSections(entry, toKtIdentifier(key), indent + 1),
  );

  return [`${spacing}object ${name} {`, ...entries, `${spacing}}`].join("\n");
};

export const generateComposeTheme = (tokens: TokenBundle): string => {
  const sections = Object.entries(tokens).map(([key, value]) =>
    buildKtSections(value, toKtIdentifier(key)),
  );

  return [
    "// Auto-generated by tools/design-tokens/build-tokens.ts",
    "package com.akari221.flashcardmaster.designsystem.tokens",
    "",
    "object DesignTokens {",
    ...sections,
    "}",
    "",
  ].join("\n");
};
