type TokenBundle = Record<string, unknown>;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const toKebabCase = (value: string) =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();

const escapeFontFamily = (value: string) =>
  /\s/.test(value) ? `"${value.replaceAll('"', '\\"')}"` : value;

const flattenCssVariables = (
  value: unknown,
  path: string[] = [],
  output: Array<{ name: string; value: string }> = [],
) => {
  if (Array.isArray(value)) {
    output.push({
      name: path.map(toKebabCase).join("-"),
      value: value.map((entry) => escapeFontFamily(String(entry))).join(", "),
    });
    return output;
  }

  if (isRecord(value)) {
    for (const [key, entry] of Object.entries(value)) {
      flattenCssVariables(entry, [...path, key], output);
    }
    return output;
  }

  const normalized =
    typeof value === "number"
      ? Number.isInteger(value)
        ? `${value}px`
        : `${value}px`
      : String(value);

  output.push({
    name: path.map(toKebabCase).join("-"),
    value: normalized,
  });

  return output;
};

const serializeTsObject = (value: unknown, indent = 0): string => {
  const spacing = "  ".repeat(indent);
  const childSpacing = "  ".repeat(indent + 1);

  if (Array.isArray(value)) {
    return `[${value.map((entry) => serializeTsObject(entry, indent)).join(", ")}]`;
  }

  if (isRecord(value)) {
    const entries = Object.entries(value).map(
      ([key, entry]) =>
        `${childSpacing}${JSON.stringify(key)}: ${serializeTsObject(entry, indent + 1)}`,
    );
    return `{\n${entries.join(",\n")}\n${spacing}}`;
  }

  return JSON.stringify(value);
};

export interface ReactThemeOutput {
  css: string;
  ts: string;
  index: string;
}

export const generateReactTheme = (tokens: TokenBundle): ReactThemeOutput => {
  const cssVariables = flattenCssVariables(tokens).sort((left, right) =>
    left.name.localeCompare(right.name),
  );

  const css = [
    "/* Auto-generated by tools/design-tokens/build-tokens.ts */",
    ":root {",
    ...cssVariables.map(({ name, value }) => `  --ds-${name}: ${value};`),
    "}",
    "",
  ].join("\n");

  const ts = [
    "// Auto-generated by tools/design-tokens/build-tokens.ts",
    `export const designTokens = ${serializeTsObject(tokens)} as const;`,
    "",
    "export const reactThemeContract = {",
    '  cssFile: "./design-tokens.css",',
    '  cssVariablePrefix: "--ds-",',
    '  rootSelector: ":root",',
    "} as const;",
    "",
  ].join("\n");

  const index = [
    'export { designTokens, reactThemeContract } from "./design-tokens";',
    "",
  ].join("\n");

  return { css, ts, index };
};
