type TokenBundle = Record<string, unknown>;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const toPascalCase = (value: string) =>
  value
    .replace(/(^|[_\-.])(\w)/g, (_, __, character: string) =>
      character.toUpperCase(),
    )
    .replace(/[^a-zA-Z0-9]/g, "");

const toSwiftIdentifier = (value: string) => {
  const normalized = toPascalCase(value);
  return /^[0-9]/.test(normalized) ? `Value${normalized}` : normalized;
};

const toSwiftLiteral = (value: unknown): string => {
  if (Array.isArray(value)) {
    return `[${value.map((entry) => toSwiftLiteral(entry)).join(", ")}]`;
  }

  if (typeof value === "number") {
    return Number.isInteger(value) ? `${value}` : `${value}`;
  }

  return `"${String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
};

const buildSwiftSections = (
  value: unknown,
  name: string,
  indent = 1,
): string => {
  const spacing = "    ".repeat(indent);

  if (!isRecord(value)) {
    return `${spacing}static let ${name} = ${toSwiftLiteral(value)}`;
  }

  const entries = Object.entries(value).map(([key, entry]) =>
    buildSwiftSections(entry, toSwiftIdentifier(key), indent + 1),
  );

  return [`${spacing}enum ${name} {`, ...entries, `${spacing}}`].join("\n");
};

export const generateSwiftTokens = (tokens: TokenBundle): string => {
  const sections = Object.entries(tokens).map(([key, value]) =>
    buildSwiftSections(value, toSwiftIdentifier(key)),
  );

  return [
    "// Auto-generated by tools/design-tokens/build-tokens.ts",
    "import Foundation",
    "",
    "enum DesignTokens {",
    ...sections,
    "}",
    "",
  ].join("\n");
};
