// Auto-generated by tools/design-tokens/build-tokens.ts
import Foundation

enum DesignTokens {
    enum Color {
        enum Primary {
            static let Value50 = "#f5f5f5"
            static let Value100 = "#e6f0ef"
            static let Value200 = "#cfe0df"
            static let Value300 = "#b8d0cf"
            static let Value400 = "#90b8b6"
            static let Value500 = "#7bacaa"
            static let Value600 = "#689a98"
            static let Value700 = "#5a8684"
            static let Value800 = "#4d7270"
            static let Value900 = "#324a48"
        }
        enum Neutral {
            static let Value0 = "#ffffff"
            static let Value50 = "#f8fafc"
            static let Value100 = "#f5f5f5"
            static let Value150 = "#f7f7f8"
            static let Value200 = "#e7ebef"
            static let Value300 = "#d9d9d9"
            static let Value400 = "#cfd9e8"
            static let Value500 = "#978d90"
            static let Value600 = "#6e6e80"
            static let Value700 = "#334155"
            static let Value800 = "#1e293b"
            static let Value900 = "#202123"
        }
        enum Status {
            static let Danger = "#e11d48"
            static let DangerSoft = "#fef2f2"
            static let Warning = "#f59e0b"
            static let WarningSoft = "#fffbeb"
            static let Success = "#10b981"
            static let SuccessSoft = "#eefdf6"
            static let Info = "#00a3ff"
            static let InfoSoft = "#eff6ff"
        }
        enum Code {
            static let Background = "#f7f8f9"
            static let Foreground = "#24292f"
            static let Border = "rgba(0, 0, 0, 0.06)"
        }
    }
    enum Spacing {
        static let Value0 = 0
        static let Value1 = 4
        static let Value2 = 8
        static let Value3 = 12
        static let Value4 = 16
        static let Value5 = 20
        static let Value6 = 24
        static let Value8 = 32
        static let Value10 = 40
        static let Value12 = 48
        static let Value16 = 64
        static let Value20 = 80
        static let Value18 = 7.2
    }
    enum Radius {
        static let Sm = 8
        static let Md = 10
        static let Lg = 12
        static let Xl = 16
        static let Value2xl = 24
        static let Value3xl = 32
        static let Pill = 999
        static let Floating = 12
    }
    enum Typography {
        enum FontFamily {
            static let Ui = ["Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"]
            static let Content = ["Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "MS PMincho", "serif"]
            static let Numeric = ["Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"]
            static let Code = ["Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"]
        }
        enum FontSize {
            static let Xs = 12.8
            static let Sm = 14
            static let SmPlus = 14.4
            static let Md = 16
            static let MdPlus = 17.6
            static let Lg = 20
            static let Value2xl = 32
        }
        enum LineHeight {
            static let Tight = 1.1
            static let Body = 1.5
            static let Comfortable = 1.625
        }
        enum FontWeight {
            static let Medium = 500
            static let Semibold = 600
            static let Bold = 700
            static let Black = 900
        }
        enum Tracking {
            static let Caps = 0.12
            static let WideCaps = 0.2
        }
    }
    enum Motion {
        enum DurationMs {
            static let Instant = 0
            static let Fast = 75
            static let Normal = 150
            static let Moderate = 200
            static let Slow = 300
            static let Toast = 500
            static let Celebration = 700
        }
        enum Easing {
            static let Standard = "ease"
            static let Emphasized = "ease-out"
            static let Linear = "linear"
        }
        enum Transition {
            static let Interactive = "150ms ease"
            static let ScreenEnter = "300ms ease-out"
            static let Progress = "500ms ease-out"
        }
    }
    enum Elevation {
        enum Shadow {
            static let Concave = "inset 0 1px 2px rgba(86, 72, 74, 0.16)"
            static let Convex = "0 1px 0 rgba(255, 255, 255, 0.9) inset, 0 -1px 0 rgba(86, 72, 74, 0.08) inset, 0 1px 2px rgba(86, 72, 74, 0.16)"
            static let Floating = "0 8px 24px rgba(15, 23, 42, 0.08)"
            static let Panel = "0 10px 24px rgba(15, 23, 42, 0.12), 0 2px 4px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95), inset 0 -1px 0 rgba(148, 163, 184, 0.25)"
            static let Soft = "0 2px 15px -3px rgba(104, 154, 152, 0.15), 0 10px 20px -2px rgba(104, 154, 152, 0.08)"
            static let Card = "0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 8px -2px rgba(0, 0, 0, 0.04)"
            static let CardHover = "0 8px 30px -4px rgba(104, 154, 152, 0.2), 0 4px 12px -2px rgba(0, 0, 0, 0.08)"
        }
        enum Blur {
            static let Floating = 12
        }
    }
    enum Semantic {
        enum Color {
            enum Background {
                static let App = "#ffffff"
                static let Sidebar = "#f7f7f8"
                static let SidebarActive = "#e7ebef"
                static let Floating = "rgba(255, 255, 255, 0.82)"
                static let Code = "#f7f8f9"
            }
            enum Border {
                static let Default = "#d9d9d9"
                static let Floating = "rgba(226, 232, 240, 0.8)"
                static let Strong = "#cfd9e8"
            }
            enum Text {
                static let Primary = "#202123"
                static let Secondary = "#6e6e80"
                static let Strong = "#1e293b"
                static let Placeholder = "#978d90"
                static let OnPrimary = "#ffffff"
            }
            enum Action {
                static let Primary = "#689a98"
                static let PrimaryHover = "#5a8684"
                static let PrimarySoft = "#e6f0ef"
                static let Accent = "#7bacaa"
            }
            enum Status {
                static let Danger = "#e11d48"
                static let Warning = "#f59e0b"
                static let Success = "#10b981"
                static let Info = "#00a3ff"
            }
        }
        enum Spacing {
            static let ControlHeight = 36
            static let ControlHeightLarge = 40
            static let PanelWidth = 320
            static let MenuMinWidth = 128
            static let SafeTopOffsetBase = 8
            static let SafeBottomPaddingBase = 80
        }
        enum Radius {
            static let Control = 10
            static let Card = 16
            static let Dialog = 12
            static let Panel = 24
            static let Hero = 32
            static let Pill = 999
        }
        enum Typography {
            static let Ui = ["Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"]
            static let Content = ["Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "MS PMincho", "serif"]
            static let Numeric = ["Zen Kaku Gothic New", "Noto Sans JP", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"]
            static let Code = ["Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"]
        }
        enum Elevation {
            static let ControlInset = "inset 0 1px 2px rgba(86, 72, 74, 0.16)"
            static let ControlRaised = "0 1px 0 rgba(255, 255, 255, 0.9) inset, 0 -1px 0 rgba(86, 72, 74, 0.08) inset, 0 1px 2px rgba(86, 72, 74, 0.16)"
            static let Floating = "0 8px 24px rgba(15, 23, 42, 0.08)"
            static let Panel = "0 10px 24px rgba(15, 23, 42, 0.12), 0 2px 4px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95), inset 0 -1px 0 rgba(148, 163, 184, 0.25)"
            static let Card = "0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 8px -2px rgba(0, 0, 0, 0.04)"
            static let CardHover = "0 8px 30px -4px rgba(104, 154, 152, 0.2), 0 4px 12px -2px rgba(0, 0, 0, 0.08)"
        }
        enum Motion {
            static let Interactive = "150ms ease"
            static let ScreenEnter = "300ms ease-out"
            static let Progress = "500ms ease-out"
        }
    }
}
